// =============================
// CLIENT EVENTS
// =============================
export const CLIENT_EVENTS = {
    CREATE_ROOM: "CREATE_ROOM",
    CONNECT: "CLIENT_CONNECT",
    DISCONNECT: "CLIENT_DISCONNECT",
    ANSWER: "CLIENT_ANSWER",
    CLOSE_GAME: "CLIENT_CLOSE_GAME",
    START_GAME: "CLIENT_START_GAME"
};

// =============================
// SERVER EVENTS
// =============================
export const SERVER_EVENTS = {
    ANSWER_QUESTION: "SERVER_ANSWER_QUESTION",
    USER_ANSWER: "USER_ANSWER",
    NEXT_QUESTION: "SERVER_NEXT_QUESTION",
    GAME_STARTED: "SERVER_GAME_STARTED",
    GAME_FINISHED: "SERVER_GAME_FINISHED",
    GAME_JOINED_USER: "SERVER_GAME_JOINED_USER",
    ALREADY_EXISTS_ROOM: "SERVER_ALREADY_EXISTS_ROOM",
    ROOM_NOT_FOUND: "SERVER_ROOM_NOT_FOUND",
    USER_LEFT: "SERVER_USER_LEFT",
    ONLY_OWNER: "SERVER_ONLY_OWNER",
    ALREADY_IN_ROOM: "SERVER_ALREADY_IN_ROOM"
};